services:
  # AServices
  service-registry:
      image: consul:1.15
      container_name: service-registry
      ports:
        - "8500:8500"
      command: agent -server -bootstrap -ui -client=0.0.0.0
      networks:
        - meal-tracker-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - meal-tracker-network
      
  api-gateway:
    build:
      context: ./api-gateway
    restart: always
    image: aminenaboulsi/api-gateway:latest
    ports:
      - "8001:80"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
        - AUTH_SERVICE_URL=http://auth-service
        - MEAL_SERVICE_URL=http://meal-service
        - NUTRITION_SERVICE_URL=http://nutrition-service
    depends_on:
      - auth-service
    networks:
      - meal-tracker-network
  auth-service:
    build:
      context: ./auth-service
    volumes:
      - ./auth-service:/var/www/html
    image: aminenaboulsi/auth-service:latest
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_DATABASE=OfferAuth
      - DB_USERNAME=OfferAuth
      - DB_PASSWORD=OfferAuth
    ports:
      - "8484:80"
    depends_on:
      - auth-db
    networks:
      - meal-tracker-network
  meal-service:
    build:
      context: ./meal-service
    command: sh -c "php artisan app:register-service-with-consul && apache2-foreground"
    ports:
      - "8000:80"
    image: aminenaboulsi/meal-service:latest
    volumes:
      - ./meal-service:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=meal-db
      - DB_PORT=5432
      - DB_DATABASE=MealsDB
      - DB_USERNAME=MealsDB
      - DB_PASSWORD=MealsDB
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      - service-registry
      - rabbitmq
    networks:
      - meal-tracker-network
  nutrition-service:
    build:
      context: ./nutrition-service
    command: sh -c "php artisan app:register-service-with-consul && apache2-foreground"
    ports:
      - "8005:80"
    volumes:
      - ./nutrition-service:/var/www/html
    image: aminenaboulsi/nutrition-service:latest
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=nutrition-db
      - DB_PORT=5432
      - DB_DATABASE=NutritionDB
      - DB_USERNAME=NutritionDB
      - DB_PASSWORD=NutritionDB
    networks:
      - meal-tracker-network
    depends_on:
      - nutrition-db
  # Databases
  auth-db:
    image: postgres:17
    container_name: AuthDB
    restart: always
    environment:
      POSTGRES_DB: "OfferAuth"
      POSTGRES_USER: "OfferAuth"
      POSTGRES_PASSWORD: "OfferAuth"
    ports:
      - "5435:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - meal-tracker-network
  meal-db:
    image: postgres:17
    container_name: MealDB
    restart: always
    environment:
      POSTGRES_DB: "MealsDB"
      POSTGRES_USER: "MealsDB"
      POSTGRES_PASSWORD: "MealsDB"
    ports:
      - "5437:5432"
    volumes:
      - meal-db-data:/var/lib/postgresql/data
    networks:
      - meal-tracker-network
  nutrition-db:
    image: postgres:17
    container_name: NutritionDB
    restart: always
    environment:
      POSTGRES_DB: "NutritionDB"
      POSTGRES_USER: "NutritionDB"
      POSTGRES_PASSWORD: "NutritionDB"
    ports:
      - "5439:5432"
    volumes:
      - nutrition-db-data:/var/lib/postgresql/data
    networks:
      - meal-tracker-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - meal-tracker-network

networks:
  meal-tracker-network:
    driver: bridge

volumes:
  auth-db-data:
  user-db-data:
  portainer-data:
  meal-db-data:
  nutrition-db-data:
  auth-service:
  meal-service:
  nutrition-service:
  gateway-service:
